# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eprotocol.proto\x12\x05proto\")\n\x06Vector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"\"\n\nConnection\x12\x14\n\x0c\x63onnected_to\x18\x01 \x01(\t\"\x95\x01\n\x04\x43\x65ll\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x65nergy_level\x18\x02 \x01(\x04\x12\x1a\n\x03pos\x18\x03 \x01(\x0b\x32\r.proto.Vector\x12\x1a\n\x03vel\x18\x04 \x01(\x0b\x32\r.proto.Vector\x12\x0b\n\x03\x64na\x18\x05 \x01(\x0c\x12&\n\x0b\x63onnections\x18\x06 \x03(\x0b\x32\x11.proto.Connection\"u\n\x10\x43\x65llComputeBatch\x12\x11\n\ttime_step\x18\x01 \x01(\x04\x12%\n\x10\x63\x65lls_to_compute\x18\x02 \x03(\x0b\x32\x0b.proto.Cell\x12\'\n\x12\x63\x65lls_in_proximity\x18\x03 \x03(\x0b\x32\x0b.proto.Cell\"\x10\n\x0e\x42igBangRequest\"5\n\x11SlaveRegistration\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0f\n\x07threads\x18\x02 \x01(\r\"\x1b\n\x19SlaveRegistrationResponse2\x96\x01\n\x16\x43\x65llInteractionService\x12K\n\x17\x43omputeCellInteractions\x12\x17.proto.CellComputeBatch\x1a\x17.proto.CellComputeBatch\x12/\n\x07\x42igBang\x12\x15.proto.BigBangRequest\x1a\x0b.proto.Cell0\x01\x32\x62\n\x18SlaveRegistrationService\x12\x46\n\x08Register\x12\x18.proto.SlaveRegistration\x1a .proto.SlaveRegistrationResponseb\x06proto3')
)




_VECTOR = _descriptor.Descriptor(
  name='Vector',
  full_name='proto.Vector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.Vector.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.Vector.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='proto.Vector.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=66,
)


_CONNECTION = _descriptor.Descriptor(
  name='Connection',
  full_name='proto.Connection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='connected_to', full_name='proto.Connection.connected_to', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=102,
)


_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='proto.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.Cell.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='energy_level', full_name='proto.Cell.energy_level', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pos', full_name='proto.Cell.pos', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vel', full_name='proto.Cell.vel', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dna', full_name='proto.Cell.dna', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='connections', full_name='proto.Cell.connections', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=105,
  serialized_end=254,
)


_CELLCOMPUTEBATCH = _descriptor.Descriptor(
  name='CellComputeBatch',
  full_name='proto.CellComputeBatch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='time_step', full_name='proto.CellComputeBatch.time_step', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cells_to_compute', full_name='proto.CellComputeBatch.cells_to_compute', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cells_in_proximity', full_name='proto.CellComputeBatch.cells_in_proximity', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=373,
)


_BIGBANGREQUEST = _descriptor.Descriptor(
  name='BigBangRequest',
  full_name='proto.BigBangRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=375,
  serialized_end=391,
)


_SLAVEREGISTRATION = _descriptor.Descriptor(
  name='SlaveRegistration',
  full_name='proto.SlaveRegistration',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='proto.SlaveRegistration.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='threads', full_name='proto.SlaveRegistration.threads', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=446,
)


_SLAVEREGISTRATIONRESPONSE = _descriptor.Descriptor(
  name='SlaveRegistrationResponse',
  full_name='proto.SlaveRegistrationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=448,
  serialized_end=475,
)

_CELL.fields_by_name['pos'].message_type = _VECTOR
_CELL.fields_by_name['vel'].message_type = _VECTOR
_CELL.fields_by_name['connections'].message_type = _CONNECTION
_CELLCOMPUTEBATCH.fields_by_name['cells_to_compute'].message_type = _CELL
_CELLCOMPUTEBATCH.fields_by_name['cells_in_proximity'].message_type = _CELL
DESCRIPTOR.message_types_by_name['Vector'] = _VECTOR
DESCRIPTOR.message_types_by_name['Connection'] = _CONNECTION
DESCRIPTOR.message_types_by_name['Cell'] = _CELL
DESCRIPTOR.message_types_by_name['CellComputeBatch'] = _CELLCOMPUTEBATCH
DESCRIPTOR.message_types_by_name['BigBangRequest'] = _BIGBANGREQUEST
DESCRIPTOR.message_types_by_name['SlaveRegistration'] = _SLAVEREGISTRATION
DESCRIPTOR.message_types_by_name['SlaveRegistrationResponse'] = _SLAVEREGISTRATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vector = _reflection.GeneratedProtocolMessageType('Vector', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.Vector)
  ))
_sym_db.RegisterMessage(Vector)

Connection = _reflection.GeneratedProtocolMessageType('Connection', (_message.Message,), dict(
  DESCRIPTOR = _CONNECTION,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.Connection)
  ))
_sym_db.RegisterMessage(Connection)

Cell = _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), dict(
  DESCRIPTOR = _CELL,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.Cell)
  ))
_sym_db.RegisterMessage(Cell)

CellComputeBatch = _reflection.GeneratedProtocolMessageType('CellComputeBatch', (_message.Message,), dict(
  DESCRIPTOR = _CELLCOMPUTEBATCH,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.CellComputeBatch)
  ))
_sym_db.RegisterMessage(CellComputeBatch)

BigBangRequest = _reflection.GeneratedProtocolMessageType('BigBangRequest', (_message.Message,), dict(
  DESCRIPTOR = _BIGBANGREQUEST,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.BigBangRequest)
  ))
_sym_db.RegisterMessage(BigBangRequest)

SlaveRegistration = _reflection.GeneratedProtocolMessageType('SlaveRegistration', (_message.Message,), dict(
  DESCRIPTOR = _SLAVEREGISTRATION,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.SlaveRegistration)
  ))
_sym_db.RegisterMessage(SlaveRegistration)

SlaveRegistrationResponse = _reflection.GeneratedProtocolMessageType('SlaveRegistrationResponse', (_message.Message,), dict(
  DESCRIPTOR = _SLAVEREGISTRATIONRESPONSE,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:proto.SlaveRegistrationResponse)
  ))
_sym_db.RegisterMessage(SlaveRegistrationResponse)



_CELLINTERACTIONSERVICE = _descriptor.ServiceDescriptor(
  name='CellInteractionService',
  full_name='proto.CellInteractionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=478,
  serialized_end=628,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComputeCellInteractions',
    full_name='proto.CellInteractionService.ComputeCellInteractions',
    index=0,
    containing_service=None,
    input_type=_CELLCOMPUTEBATCH,
    output_type=_CELLCOMPUTEBATCH,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BigBang',
    full_name='proto.CellInteractionService.BigBang',
    index=1,
    containing_service=None,
    input_type=_BIGBANGREQUEST,
    output_type=_CELL,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_CELLINTERACTIONSERVICE)

DESCRIPTOR.services_by_name['CellInteractionService'] = _CELLINTERACTIONSERVICE


_SLAVEREGISTRATIONSERVICE = _descriptor.ServiceDescriptor(
  name='SlaveRegistrationService',
  full_name='proto.SlaveRegistrationService',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=630,
  serialized_end=728,
  methods=[
  _descriptor.MethodDescriptor(
    name='Register',
    full_name='proto.SlaveRegistrationService.Register',
    index=0,
    containing_service=None,
    input_type=_SLAVEREGISTRATION,
    output_type=_SLAVEREGISTRATIONRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SLAVEREGISTRATIONSERVICE)

DESCRIPTOR.services_by_name['SlaveRegistrationService'] = _SLAVEREGISTRATIONSERVICE

# @@protoc_insertion_point(module_scope)
